"""empty message

Revision ID: 239a3650b0f8
Revises: e8deca2c18fb
Create Date: 2024-08-12 14:55:41.718980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '239a3650b0f8'
down_revision = 'e8deca2c18fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('penjualan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datetime', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('penjualan', schema=None) as batch_op:
        batch_op.drop_column('datetime')

    # ### end Alembic commands ###
