"""empty message

Revision ID: e8deca2c18fb
Revises: 
Create Date: 2024-08-12 10:13:58.066515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8deca2c18fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pabrik',
    sa.Column('id_pabrik', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id_pabrik')
    )
    op.create_table('aroma',
    sa.Column('id_aroma', sa.Integer(), nullable=False),
    sa.Column('id_pabrik', sa.Integer(), nullable=True),
    sa.Column('nama', sa.String(length=20), nullable=True),
    sa.Column('harga', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_pabrik'], ['pabrik.id_pabrik'], ),
    sa.PrimaryKeyConstraint('id_aroma')
    )
    op.create_table('penjualan',
    sa.Column('id_penjualan', sa.Integer(), nullable=False),
    sa.Column('id_pabrik', sa.Integer(), nullable=True),
    sa.Column('id_aroma', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('harga', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_aroma'], ['aroma.id_aroma'], ),
    sa.ForeignKeyConstraint(['id_pabrik'], ['pabrik.id_pabrik'], ),
    sa.PrimaryKeyConstraint('id_penjualan')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('penjualan')
    op.drop_table('aroma')
    op.drop_table('pabrik')
    # ### end Alembic commands ###
